config/routes.rb
Rails.application.routes.draw do
  resources :sample_resources

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  include Typus::Orm::ActiveRecord::AdminUser
end

app/models/sample_resource.rb
class SampleResource < ActiveRecord::Base
end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < Admin::ResourcesController
end

app/controllers/admin/sample_resources_controller.rb
class Admin::SampleResourcesController < Admin::ResourcesController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sample_resources_controller.rb
class SampleResourcesController < ApplicationController
  before_action :set_sample_resource, only: [:show, :edit, :update, :destroy]

  # GET /sample_resources
  # GET /sample_resources.json
  def index
    @sample_resources = SampleResource.all
  end

  # GET /sample_resources/1
  # GET /sample_resources/1.json
  def show
  end

  # GET /sample_resources/new
  def new
    @sample_resource = SampleResource.new
  end

  # GET /sample_resources/1/edit
  def edit
  end

  # POST /sample_resources
  # POST /sample_resources.json
  def create
    @sample_resource = SampleResource.new(sample_resource_params)

    respond_to do |format|
      if @sample_resource.save
        format.html { redirect_to @sample_resource, notice: 'Sample resource was successfully created.' }
        format.json { render :show, status: :created, location: @sample_resource }
      else
        format.html { render :new }
        format.json { render json: @sample_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sample_resources/1
  # PATCH/PUT /sample_resources/1.json
  def update
    respond_to do |format|
      if @sample_resource.update(sample_resource_params)
        format.html { redirect_to @sample_resource, notice: 'Sample resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample_resource }
      else
        format.html { render :edit }
        format.json { render json: @sample_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sample_resources/1
  # DELETE /sample_resources/1.json
  def destroy
    @sample_resource.destroy
    respond_to do |format|
      format.html { redirect_to sample_resources_url, notice: 'Sample resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample_resource
      @sample_resource = SampleResource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_resource_params
      params.fetch(:sample_resource, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/dashboard/_sidebar.html.erb
自分で置き換えたview

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TypusTestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sample_resources/_form.html.erb
<%= form_for(@sample_resource) do |f| %>
  <% if @sample_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample_resource.errors.count, "error") %> prohibited this sample_resource from being saved:</h2>

      <ul>
      <% @sample_resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sample_resources/edit.html.erb
<h1>Editing Sample Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample_resource %> |
<%= link_to 'Back', sample_resources_path %>

app/views/sample_resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sample Resources</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_resources.each do |sample_resource| %>
      <tr>
        <td><%= link_to 'Show', sample_resource %></td>
        <td><%= link_to 'Edit', edit_sample_resource_path(sample_resource) %></td>
        <td><%= link_to 'Destroy', sample_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample resource', new_sample_resource_path %>

app/views/sample_resources/new.html.erb
<h1>New Sample Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', sample_resources_path %>

app/views/sample_resources/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sample_resource_path(@sample_resource) %> |
<%= link_to 'Back', sample_resources_path %>